communitiesuk/funding-service-design-post-award-docker-runner

- docker-compose.yml
https://trello.com/c/bWlBXIxP/337-add-front-end-to-docker-runner
Add frontend
- [NA] README and other documentation has been updated / added (if needed)
> [#PAB-337] add frontend

- docker-compose.yml
- scripts/db-race-conditions-windows-fix.sh
- scripts/reset-all-repos.sh
https://trello.com/c/zZ7XRHeA/295-setup-postgres-database
Connect data-store to postgres
> [#PAB-295] connect data-store to postgres db

- scripts/db-race-conditions-windows-fix.sh
fixed syntax error in windows-fix sh
> fixed syntax error in windows-fix sh

- docker-compose.yml
- scripts/db-race-conditions-windows-fix.sh
- scripts/reset-all-repos.sh
- scripts/reset-empty-db.sh
Adds a script that tears down the existing db and starts up a fresh empty one in its place.
> [BAU] reset empty db script

- docker-compose.yml
Add submit tool to docker compose.
> BAU: adding submit

- docker-compose.yml
Add submit url to authenticator
> BAU: add submit url to authenticator

- scripts/db-race-conditions-windows-fix.sh
- scripts/reset-empty-db.sh
Fixes a bug preventing the creation of the databases.
> BAU: fix tty issue

- docker-compose.yml
- set AWS dev creds as constants 
> [SMD-189] set AWS creds as constant

- docker-compose.yml
- points data-store to correct localstack endpoint
> [BAU] point data-store to correct localstack endpoint

- scripts/db-race-conditions-windows-fix.sh
- scripts/reset-empty-db.sh
https://dluhcdigital.atlassian.net/browse/FMD-8
Adding additional DB name to setup scripts, to separate local app DB from unit test DB.
This will prevent Pytest setup/teardown fixtures affecting the scope of a local DB .
> [FMD-8] create separate DB instance for tests

- README.md
- docker-compose.yml
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140/backlog?selectedIssue=SMD-495
Adds more detail and removes unused links from readme
> SMD-495 app required repo details to readme

- README.md
- scripts/localstack-script.sh
https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139/backlog?selectedIssue=FMD-156
Adds a new S3 bucket to the localstack instance for successfully ingested files
The new bucket should be available at http://data-store-successful-files-dev.s3.localhost.localstack.cloud:4566/
> create ingested files bucket on localstack

- scripts/bootstrap.sh
Add n1 flag to xargs command to make it Linux friendly.
_No ticket was created for this change_
> Add n1 flag to xargs command

- scripts/localstack-script.sh
Adding s3 bucket in docker runner script to create a new bucket for find data.
> New s3 bucket for find data

- docker-compose.yml
Adding FIND_SERVICE_BASE_URL environment variable to docker-compose.yml.
> Adding FIND_SERVICE_BASE_URL to docker-compose.yml

- docker-compose.yml
Add Celery service to docker compose file for running background tasks. 
Ticket: https://dluhcdigital.atlassian.net/browse/FPASF-102
> Celery service setup

- README.md
- docker-compose.yml
- scripts/vs-code-debug-script.sh
In preparation for the combined post award service, this removes the separate submit and find services. It also updates URLs to those services to hit the correct domains on localhost, which are required for routing correctly.
> Remove separate find+submit services

- docker-compose.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_ 
> Fix cookie domain and authenticator host for monolith

- docker-compose.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_ 
> Separate redis DBs by use and fix download ports

- README.md
- docker-compose.yml
- Adjust README
- Pre-populate sample data
> Pre-populate sample data

- docker-compose.yml
This value was missing which is needed for locally testing with Authenticator
Should go to correct host is `DEBUG_USER=False`
> BAU: add authenticator host to data-store
